# Generated by Django 5.2.5 on 2025-08-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prompt",
            old_name="prompt_text",
            new_name="prompt_template",
        ),
        migrations.AddField(
            model_name="prompt",
            name="variables",
            field=models.JSONField(default=list),
        ),
    ]
