# Generated by Django 5.2.5 on 2025-08-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_prompt_text_prompt_prompt_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="variables",
            field=models.JSONField(default=dict),
        ),
    ]
