# Generated by Django 5.2.5 on 2025-08-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_prompt_variables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
