# Generated by Django 5.2.5 on 2025-09-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_category_prompt_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="output_specification",
            field=models.TextField(blank=True, null=True),
        ),
    ]
