# Generated by Django 5.2.5 on 2025-09-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_prompt_output_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='output_specification',
            new_name='output_format',
        ),
    ]
