# Generated by Django 5.2.5 on 2025-10-22 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="prompt_response",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="api_information",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboard",
            name="diagrams",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
