# Generated by Django 5.2.5 on 2025-11-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_remove_dashboard_prompt_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="used_prompts",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
